### ISSUE TITLE
bugi: palvelu käyttää käyttöjärjestelmän/selaimen kieliasetuksia oletuskielen valintaan

### ISSUE THREAD

**Issue by esuomi** [vesanieminen/ElectricityCostDashboard#16]
Moi,

Näköjään kun Liukuriin tulee, niin oletuskieli sattuukin olemaan englanti, oletetusti selaimen asetuksista. Kuten varmasti näin suomalaisena ymmärrät, johtuen pitkälti yhdysvaltalaisten firmojen huonoista käännöksistä sekä varsinkin ongelmien googlauksen vaikeudesta, käyttöjärjestelmän ja sitä myöten selaimen kieli harvoin kertoo, mikä on käyttäjän oikeasti preferoima kieli.

Parempi nyrkkisääntö onkin, että jos domain josta tullaan on .fi -> kieli on suomi, .se -> kieli on ruotsi, .com -> kieli on englanti jne.

Tämä on toki kansainvälisessä kontekstissa vielä vaikeampaa, koska esmes espanjaa puhuvat eteläamerikkalaiset eivät noin pääsääntöisesti osaa puolestaan englantia, jenkit ottavat mieluummin dubbauksen kuin tekstityksen, Quebecissa asustavat haluavat oletuksena kaiken ranskaksi vaikka ovatkin kanadalaisia jne. jne. Toki tässä kohtaa on hyvä rajata kieliongelmat Suomen rajojen sisään, koska ongelmaan ei ole muuten mitään mahdollisuutta löytää yhtä ratkaisua.

**Comment by vesanieminen** [comment]
Ymmärrän kyllä pointtisi, mutta itse olen sitä mieltä, että selaimen kieli saa määrittää sovelluksen alkuperäisen kielen. Veikkaan, että niitä henkilöitä on paljon vähemmän, jotka ovat suomalaisia ja tykkäävät pitää selaimen englanninkielisenä kuin niitä, jotka asuvat Suomessa, eivät puhu suomea ja pitävät selaimen kielen englanninkielisenä 🙂

Joka tapauksessa nyt, kun kerran vaihdat kielen suomeksi niin sovellus muistaa sen valinnan ja tarjoilee sinulle jatkossa vain suomenkielisen sisällön.
