### ISSUE TITLE
Fixed price calculated too high?

### ISSUE THREAD

**Issue by rhk** [vesanieminen/ElectricityCostDashboard#3]
![image](https://user-images.githubusercontent.com/404543/196598941-0c40723d-be62-4ea4-aa20-eefcc899a927.png)

In the attached image the fixed price is not calculated correctly: 
266kWh with 30/kWh is not 339€, I think it should be around 266*0,3=80€

Also I checked what is the fixed price using the given average spot price:
![image](https://user-images.githubusercontent.com/404543/196599631-c3c74705-c207-4f8e-8160-842a29c39117.png)
and the fixed price is still about 4 times too high.

What do I miss here, or is there something wrong in the formula? 

Anyway, thanks for the great tool, this is something I've been thinking for a while!

**Comment by vesanieminen** [comment]
There was an issue earlier today but it should be fixed now. Can you please try again and let me know if it is ok for you? When I implemented the date range selector last night I forgot to apply it to the fixed price calculation 😛

**Comment by rhk** [comment]
Seems to work, thanks :)
