### ISSUE TITLE
ParseException when uploading CSV file with missing readings

### ISSUE THREAD

**Issue by jruusu** [vesanieminen/ElectricityCostDashboard#6]
Given a CSV file with missing readings, upload at https://liukuri.fi/laskuri fails with this error message:
> Upload failed: java.lang.RuntimeException: java.text.ParseException: Unparseable number: "null"

A few examples of such records from Fingrid:
```csv
<ID_REDACTED>;8716867000030;PT1H;kWh;2022-11-21T07:00:00Z;null;MISSING
<ID_REDACTED>;8716867000030;PT1H;kWh;2022-11-21T08:00:00Z;null;MISSING
<ID_REDACTED>;8716867000030;PT1H;kWh;2022-11-21T09:00:00Z;null;MISSING
```

Thank you for a great service, and another thank you for making the source code public!

**Comment by vesanieminen** [comment]
This should be fixed now. Please let me know if that is not the case and I'll revisit it.

**Comment by jruusu** [comment]
Looks good, the same file with missing values now gets parsed flawlessly. Thanks!
