### ISSUE TITLE
Feature request: Temperature observations

### ISSUE THREAD

**Issue by maakuth** [vesanieminen/ElectricityCostDashboard#8]
The temperature forecast is already there, it would be great to pair it with temperature observation data. It should be available from the FMI open data: https://en.ilmatieteenlaitos.fi/open-data-manual

**Comment by vesanieminen** [comment]
Thanks. I actually looked at that FMI API earlier and noticed that it would take a bit of effort to read the data and decided so far against adding it. Currently all the APIs I'm using are REST + JSON and just so nice to read and consume. If you happen to find a good REST API for FMI I would love to put it to use 🙂

Sorry for the delay, I just noticed this ticket (looks like I don't get any email notifications about these).

**Comment by maakuth** [comment]
This one seems like a reasonably straightforward API, query by GET parameters and you'll get results back in XML:
https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::observations::weather::hourly::multipointcoverage&place=H%C3%A4meenlinna

Of course the XML seems to be just a bloated encapsulation for the real data that's in gml:doubleOrNilReasonTupleList element as space separated numerals :smile:. 

I'm looking into implementing FMIService for it myself, expect a PR when I have time to do it.

**Comment by vesanieminen** [comment]
I'd be very happy to include such a PR 😛

**Comment by maakuth** [comment]
I just learned about an API that responds with JSON. Even better.
https://www.ilmatieteenlaitos.fi/api/weather/observations?fmisid=101150&observations=true
